apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-depl
  annotations:
    keel.sh/policy: force     # update policy (available: patch, minor, major, all, force)
    keel.sh/trigger: poll     # enable active repository checking (webhooks and GCR would still work)
    keel.sh/pollSchedule: "@every 30m"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accountservice
  template:
    metadata:
      labels:
        app: accountservice
    spec:
      containers:
        - name: accountservice
          image: boostedpenguin/accountservice:latest
          envFrom:
            - configMapRef:
                name: accounts-config
          imagePullPolicy: Always      
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: accountservice
  ports:
  - name: accountservice
    protocol: TCP
    port: 80
    targetPort: 80
  - name: accountgrpc
    protocol: TCP
    port: 888
    targetPort: 888