apiVersion: apps/v1
kind: Deployment
metadata:
  name: questions-depl
  annotations:
    keel.sh/policy: force     # update policy (available: patch, minor, major, all, force)
    keel.sh/trigger: poll     # enable active repository checking (webhooks and GCR would still work)
    keel.sh/pollSchedule: "@every 30m"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: questionservice
  template:
    metadata:
      labels:
        app: questionservice
    spec:
      containers:
        - name: questionservice
          image: boostedpenguin/questionservice:latest
          envFrom:
            - configMapRef:
                name: questions-config
          imagePullPolicy: Always 
---
apiVersion: v1
kind: Service
metadata:
  name: questions-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: questionservice
  ports:
  - name: questionservice
    protocol: TCP
    port: 80
    targetPort: 80